# Author: David
# Date: 13/05/2020

# Docker compose configuration to bring up all microservices

version: "3"

services:

  user-service:
    image: user-service
    build:
      context: ./users_service
      args:
        port: ${USER_SERVICE_PORT}
        sqlite_db_path: ${DEFAULT_SQLITE_DB_PATH}
        sql_logger: ${SQL_LOGGER}
        jwt_secret: ${JWT_SECRET}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - user-db:/user-service/persistence


  mysql:
    image: mysql-catalog-service
    build:
      context: ./mysql_catalog_service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_catalog_service/sql_scripts:/docker-entrypoint-initdb.d/
      - mysql-db:/var/lib/mysql


  catalog-service:
    image: catalog-service
    build:
      context: ./catalogue_service
      args:
        port: ${CATALOG_SERVICE_PORT}
        sql_host: mysql
        sql_username: root
        sql_password: ${MYSQL_ROOT_PASSWORD}
        sql_database: shop
        sql_logger: ${SQL_LOGGER}
    ports:
      - "${CATALOG_SERVICE_PORT}:${CATALOG_SERVICE_PORT}"
    depends_on:
      - mysql


  cart-service:
    image: cart-service
    build:
      context: ./cart_service
      args:
        port: ${CART_SERVICE_PORT}
        sqlite_db_path: ${DEFAULT_SQLITE_DB_PATH}
        sql_logger: ${SQL_LOGGER}
    ports:
      - "${CART_SERVICE_PORT}:${CART_SERVICE_PORT}"
    volumes:
      - cart-db:/cart-service/persistence


  order-service:
    image: order-service
    build:
      context: ./order_service
      args:
        port: ${ORDER_SERVICE_PORT}
        sqlite_db_path: ${DEFAULT_SQLITE_DB_PATH}
        sql_logger: ${SQL_LOGGER}
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    volumes:
      - order-db:/order-service/persistence


  frontend-service:
    image: frontend-service
    build:
      context: ./frontend
      args:
        hostname: ${HOSTNAME}
        port: ${FRONT_END_SERVICE_PORT}
        user_service_port: ${USER_SERVICE_PORT}
        catalog_service_port: ${CATALOG_SERVICE_PORT}
        cart_service_port: ${CART_SERVICE_PORT}
        order_service_port: ${ORDER_SERVICE_PORT}
    ports:
      - "${FRONT_END_SERVICE_PORT}:${FRONT_END_SERVICE_PORT}"
    depends_on:
      - user-service
      - catalog-service
      - cart-service
      - order-service

volumes: 
  cart-db:
  mysql-db:
  order-db:
  user-db:
