# Author: David
# Date: 13/05/2020

# Docker compose configuration to bring up all microservices

version: "3"

services:

  user-service:
    image: user-service
    build:
      context: ./users_service
      args:
        port: 3001
        sqlite_db_path: "persistence/database.sqlite"
        sql_logger: "false"
        jwt_secret: secret
    volumes:
      - user-db:/user-service/persistence


  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - mysql-db:/var/lib/mysql


  catalog-service:
    image: catalog-service
    build:
      context: ./catalogue_service
      args:
        port: 3002
        sql_host: mysql
        sql_username: root
        sql_password: mypass
        sql_database: shop
        sql_logger: "false"


  cart-service:
    image: cart-service
    build:
      context: ./cart_service
      args:
        port: 3003
        sqlite_db_path: "persistence/database.sqlite"
        sql_logger: "false"
    volumes:
      - cart-db:/cart-service/persistence


  order-service:
    image: order-service
    build:
      context: ./order_service
      args:
        port: 3004
        sqlite_db_path: "persistence/database.sqlite"
        sql_logger: "false"
    volumes:
      - order-db:/order-service/persistence


  frontend-service:
    image: frontend-service
    build:
      context: ./front_end_service
      args:
        port: 8079
        user_service_dest: user-service
        user_service_port: 3001
        catalog_service_dest: catalog-service
        catalog_service_port: 3002
        cart_service_dest: cart-service
        cart_service_port: 3003
        order_service_dest: order-service
        order_service_port: 3004
    ports:
      - "8079:8079"

volumes: 
  cart-db:
  mysql-db:
  order-db:
  user-db:
  
